---
title: "Caracterização de cargas de trabalho"
output: html_notebook
---

# Sobre este documento

- Este arquivo é um *Notebook* do tipo *R Markdown*. [Guia de como começar](https://rmarkdown.rstudio.com/lesson-1.html).

- Você pode executar um bloco de código colocando o cursor sobre ele e apertando *Ctrl+Shift+Enter*.

- *Ctrl+Alt+I* insere um novo bloco de código.

----

# 1. Carregando e tratando o arquivo de log
Dependências: rematch

```{r}
library("rematch")

# Não foi identificado o significado do ultimo campo.
# O campo de _url_ pode ainda ser melhor "dividido": separar entre o caminho e os parâmetros passados.
pattern <- r"{^(?<client>\S+) - - \[(?<datetime>[\s\S]+)\] "(?<method>\w+) (?<url>\S+) (?<version>\S+)" (?<status>\d+) (?<size>\d+) "(?<referer>\S+)" "(?<agent>[\s\S]+)" "(?<ip_desconhecido>\S+)"$}"

df = data.frame()
for (line in readLines("access-head-2000.log")){
	row <- rematch::re_match(pattern, line)
	df <- rbind(df, row)
}

# as.factor transforma em variáveis categóricas

df$.match <- NULL
df$client <- as.factor(df$client)
df$datetime <- as.POSIXct(df$datetime, format = "%d/%b/%Y:%T %z")
df$method <- as.factor(df$method)
df$url <- as.factor(df$url)
df$version <- as.factor(df$version)
df$status <- as.factor(df$status)
df$size <- as.integer(df$size)
df$referer[df$referer == "-"] <- NA
df$referer <- as.factor(df$referer)
df$agent <- as.factor(df$agent)
df$ip_desconhecido[df$ip_desconhecido == "-"] <- NA
df$ip_desconhecido <- as.factor(df$ip_desconhecido)

print(df)
```

# 2. Analisando o tamanho das requisições
```{r}
library("ggplot2")
```


```{r}
ggplot(df[0:100,], aes(x = seq_along(size), y = sort(size), color=method)) + scale_y_continuous(labels = scales::comma) + geom_point()
```

```{r}
# ordenar por tamanho
#subset <- df_size_ordered[0:500,]$size
#mean(subset)
#sd(subset)
#100 * sd(subset) / mean(subset)
```

```{r}
df_size_ordered <- df[order(df$size),]
```


```{r}
hist(df$size, breaks = 300)
```

```{r}
hist(df[df$size < 100000,]$size, breaks = 8)
```
```{r}
nrow(df[df$size < 60000,])
```


```{r}
plot(df$datetime)
2000/as.numeric(difftime(max(df$datetime), min(df$datetime), units = "secs"))
```
